import Link from "next/link";

export const metadata = {
  title: "My Next JS App",
  description: "Generated by NM Tafe",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          {/* Navigation components */}
          <Link href="/">Home</Link>
          <Link href="/about">About Us</Link>
          <Link href="/api/user">Get User</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
